// Generated by scripts/update-fallback.js — do not edit by hand.
// Source: https://getbible.net (public domain / freely distributable translations).
export const FALLBACK = Object.freeze({
  "en": {
    "chapter": 23,
    "verse": 1,
    "text": "Yahweh is my shepherd: I shall lack nothing."
  },
  "pt": {
    "chapter": 23,
    "verse": 1,
    "text": "O SENHOR é meu pastor, nada me faltará."
  },
  "es": {
    "chapter": 23,
    "verse": 1,
    "text": "JEHOVÁ es mi pastor; nada me faltará."
  },
  "fr": {
    "chapter": 23,
    "verse": 1,
    "text": "Cantique de David. L’Éternel est mon berger : je ne manquerai de rien."
  },
  "de": {
    "chapter": 23,
    "verse": 1,
    "text": "Ein Psalm von David. Jehova ist mein Hirte, mir wird nichts mangeln."
  },
  "it": {
    "chapter": 23,
    "verse": 1,
    "text": "Salmo di Davide. L’Eterno è il mio pastore, nulla mi mancherà."
  },
  "nl": {
    "chapter": 23,
    "verse": 1,
    "text": "Een psalm van David. De HEERE is mijn Herder, mij zal niets ontbreken."
  },
  "ru": {
    "chapter": 22,
    "verse": 1,
    "text": "Господь - Пастырь мой; я ни в чем не буду нуждаться:"
  },
  "uk": {
    "chapter": 22,
    "verse": 1,
    "text": "Господь — то мій Па́стир, тому́в недоста́тку не буду, —"
  },
  "pl": {
    "chapter": 23,
    "verse": 1,
    "text": "Psalm Dawidowy. Pan jest pasterzem moim, na niczem mi nie zejdzie."
  },
  "cs": {
    "chapter": 23,
    "verse": 1,
    "text": "Žalm Davidův. Hospodin jest můj pastýř, nebudu míti nedostatku."
  },
  "ro": {
    "chapter": 23,
    "verse": 1,
    "text": "Domnul este Păstorul meu: nu voi duce lipsă de nimic."
  },
  "hu": {
    "chapter": 23,
    "verse": 1,
    "text": "Dávid zsoltára. Az Úr az én pásztorom; nem szűkölködöm."
  },
  "sv": {
    "chapter": 23,
    "verse": 1,
    "text": "En psalm av David. HERREN är min herde, mig skall intet fattas,"
  },
  "da": {
    "chapter": 23,
    "verse": 1,
    "text": "En Salme af David. HERREN er min Hyrde, mig skal intet fattes,"
  },
  "nb": {
    "chapter": 23,
    "verse": 1,
    "text": "En salme av David. Herren er min hyrde, mig fattes intet."
  },
  "nn": {
    "chapter": 23,
    "verse": 1,
    "text": "Ein salme av David. Herren er min hyrding, det vantar meg ingen ting."
  },
  "fi": {
    "chapter": 23,
    "verse": 1,
    "text": "Daavidin virsi. Herra on minun paimeneni, ei minulta mitään puutu."
  },
  "el": {
    "chapter": 23,
    "verse": 1,
    "text": "«Ψαλμός του Δαβίδ.» Ο Κύριος είναι ο ποιμήν μου· δεν θέλω στερηθή ουδενός."
  },
  "he": {
    "chapter": 23,
    "verse": 1,
    "text": "מִזְמ֥וֹר לְדָוִ֑ד יְהוָ֥ה רֹ֝עִ֗י לֹ֣א אֶחְסָֽר׃"
  },
  "ar": {
    "chapter": 23,
    "verse": 1,
    "text": "ٱلرَّبُّ رَاعِيَّ فَلَا يُعْوِزُنِي شَيْءٌ."
  },
  "zh-Hans": {
    "chapter": 23,
    "verse": 1,
    "text": "（大卫的诗。）耶和华是我的牧者，我必不致缺乏。"
  },
  "zh-Hant": {
    "chapter": 23,
    "verse": 1,
    "text": "（大衛的 詩。）耶和華 是我的牧者，我必不 致缺乏。"
  },
  "ja": {
    "chapter": 23,
    "verse": 1,
    "text": "主はわたしの牧者であって、わたしには乏しいことがない。"
  },
  "ko": {
    "chapter": 23,
    "verse": 1,
    "text": "여호와는 나의 목자시니 내가 부족함이 없으리로다"
  },
  "vi": {
    "chapter": 23,
    "verse": 1,
    "text": "Ðức Giê-hô-va là Ðấng chăn giữ tôi: tôi sẽ chẳng thiếu thốn gì."
  },
  "tl": {
    "chapter": 23,
    "verse": 1,
    "text": "Ang Panginoon ay aking pastor; hindi ako mangangailangan."
  },
  "af": {
    "chapter": 23,
    "verse": 1,
    "text": "'n Psalm van Dawid. Die HERE is my herder; niks sal my ontbreek nie."
  },
  "sq": {
    "chapter": 23,
    "verse": 1,
    "text": "Zoti është bariu im, asgjë nuk do të më mungojë."
  },
  "hr": {
    "chapter": 23,
    "verse": 1,
    "text": "Psalam. Davidov. Jahve je pastir moj: ni u čem ja ne oskudijevam;"
  },
  "sr": {
    "chapter": 23,
    "verse": 1,
    "text": "Господ је пастир мој, ништа ми неће недостајати."
  },
  "tr": {
    "chapter": 23,
    "verse": 1,
    "text": "RAB çobanımdır, Eksiğim olmaz."
  },
  "th": {
    "chapter": 23,
    "verse": 1,
    "text": "พระเยโฮวาห์ทรงเป็นผู้เลี้ยงดูของข้าพเจ้า ข้าพเจ้าจะไม่ขัดสน"
  },
  "lt": {
    "chapter": 23,
    "verse": 1,
    "text": "Viešpats yra mano ganytojas – aš nestokosiu."
  },
  "eo": {
    "chapter": 23,
    "verse": 1,
    "text": "La Eternulo estas mia paŝtisto; mi mankon ne havos."
  },
  "la": {
    "chapter": 22,
    "verse": 1,
    "text": "Psalmus David. Dominus regit me, et nihil mihi deerit :"
  }
});
